# Generated by Django 4.0.3 on 2022-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='Aage',
            new_name='Abday',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Aemail',
            new_name='Acontactnum',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Agender',
            new_name='Aemailadd',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Aname',
            new_name='Afirstname',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Aphonenumber',
            new_name='Alastname',
        ),
        migrations.AddField(
            model_name='personal',
            name='Amiddlename',
            field=models.TextField(default=''),
        ),
    ]
